
export interface CrawlSettings {
  url: string;
  maxPosts: number;
  maxImagesPerPost: number;
  minDelay: number;
  maxDelay: number;
  useSmartNaming: boolean;
}

export enum LogType {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  SYSTEM = 'SYSTEM'
}

export interface LogEntry {
  id: string;
  timestamp: Date;
  message: string;
  type: LogType;
}

export interface TikTokImage {
  url: string; // The actual image URL (simulated)
  originalName: string;
}

export interface CrawledPost {
  id: string;
  username: string;
  originalLink: string;
  crawledAt: string;
  caption: string;
  hashtags: string[];
  images: TikTokImage[];
  smartTitle?: string; // Generated by Gemini
  isCarousel: boolean;
}

// --- NEW TYPES FOR PHASE 1 & 2 ---

export type QueueStatus = 'pending' | 'processing' | 'done' | 'failed';

export interface QueuedPost {
  id: string;
  url: string;
  status: QueueStatus;
  type: 'image' | 'video'; // We only care about image
  scannedAt: number;
  errorMsg?: string;
  data?: CrawledPost; // To store result temporarily
}

// --- SHOPEE TYPES ---

export interface ShopeeProduct {
  itemid: number;
  shopid: number;
  shop_name?: string; // New field for Shop Name
  name: string;
  image: string; // Main image ID
  images: string[]; // List of image IDs
  price: number;
  stock: number;
  historical_sold: number;
  rating_star: number;
  currency: string;
  status: 'active' | 'inactive';
  category?: string; // Changed to string to support dynamic granular categories
  set_code?: string; // New field: Mã Set (VD: S260107_200159_01)
}

// --- COLLAGE TYPES ---

export interface LogoBox {
    hasLogo: boolean;
    ymin: number; // 0-1000 scale
    xmin: number;
    ymax: number;
    xmax: number;
}

export interface LocalImage {
  id: string;
  file: File;
  previewUrl: string;
  hasPerson?: boolean; // AI result
  logoInfo?: LogoBox; // AI result for logo position
  isSelected: boolean;
  customText?: string; // Text to overlay (e.g. "Set 1")
}

export type LayoutType = '2x1' | '1x2' | '2x2' | '4x1' | '1x1';

export interface CollageConfig {
  width: number;
  height: number;
  gap: number;
  backgroundColor: string;
  removeLogo: boolean; // Toggle for user
  autoCrop: boolean; // Toggle for trimming white borders
  textPosition: 'bottom-left' | 'center'; // Config
  globalText?: string; // New: Global text for the entire collage (used in center mode)
}

// --- BATCH COLLAGE TYPES ---
export interface BatchFolderItem {
    id: string;
    folderName: string; // Acts as Set Code
    originalImages: File[]; // Raw files
    processedImages: LocalImage[]; // Analyzed images
    status: 'pending' | 'analyzing' | 'generating' | 'done' | 'failed' | 'skipped';
    resultImage: string | null; // DataURL of final collage
    statusMessage?: string;
    selectedLayout?: LayoutType;
    captionContent?: string; // NEW: Stores generated text file content
    customName?: string; // NEW: Allows user to rename the set manually
    customMeta?: { filename: string };
}